#!/bin/sh
 
gcloud compute ssh app@demo --zone us-central1-a <<EOF
#ssh app@app <<EOF
  sudo su
  cd ~
  git clone https://github.com/jrobinson17/LoginDemoApp
  cd ~/LoginDemoApp
  git pull
  npm install -g forever
  npm install --production
  npm install -d
  forever start app.js
  forever restartall
  exit
EOF
